### ISSUE TITLE
Design visualizations of audio.

### ISSUE THREAD

**Issue by chihuahua** [GoogleChrome/audion#72]
It may be useful to visualize audio entering the numeric input channel of each `AudioNode`. First, we should research and justify what type of visualization(s) would be most useful - a waveform/oscilloscope? A histogram of the frequency domain?

For starters, a user may want to know whether any audio is going into an input at all. Beyond that, I wonder what information is most useful to visualize.

After making that design call, we use native `AnalyserNode`s to collect the data needed for visualization. That logic will reside in `js/entry-points/tracing.js`.

**Comment by micbuffa** [comment]
I wrote both a frequency analyser and an oscilloscope with a stabilization feature for waveforms (like on real oscilloscopes). They are both ES6 classes that inherit from the AnalyserNode (and that do not work when your extension is enabled -> I just posted an issue about that). I'm still working on them (removing external dependencies, adding some optional dat-gui widgets, etc.).
Both are fully resizable with labels and fonts adjusted automatically.

You can give a look at current versions in case they can help:

- Frequency analyser: https://codepen.io/w3devcampus/pen/GWGdjK?editors=0010
- Oscilloscope: http://jsbin.com/cawenaj/edit?js,output, I also started made it an ES6 class that inherits from the AnalyserNode, but I haven't added the sensibility slider yet.

You can see both of them in action with my tube guitar amp simulation (does not work when your extension is enabled): https://wasabi.i3s.unice.fr/AmpSimFA

**Comment by chihuahua** [comment]
That might be exactly we need. Both visualizations seem well thought-out.

I think I need authorization to see https://wasabi.i3s.unice.fr/AmpSimFA
Awesome, awesome work. We have to fix #73.

**Comment by rtoy** [comment]
While we're wishing for things, include a spectrogram. :-)

I think this needs some careful thought.  To support visualization, you have to insert an AnalyserNode from this app into the applications audio graph.  This is intrusive.  You have to add some kind of timer to get the data.  That impacts CPU usage on the main thread.  In addition, because audion doesn't know about GCed objects, the point where you want to add visualization may no longer exist.  Or by adding it, the object may not be GCed anymore, breaking how the app might work.

There's also the issue of where this gets displayed. My dev console window is usually at the bottom of the tab so space is limited. I can pop it out when necessary, but then it covers up even more precious screen space.

While I'd love to have a built-in visualizer that I can just attach when needed (my graphs are almost always static), general usage seems complicated.  Actually, for my usage, canopy works perfectly except that you can't visualize arbitrary nodes.  But that can be fixed by sending the node output as another channel to the destination.  Kind of painful, but doable.

**Comment by micbuffa** [comment]
https://wasabi.i3s.unice.fr/AmpSimFA/ is public now. It's a recreation of a
Marshall JCM800 tube amp with measure tools (freq analyzer, oscilloscope,
the ones I shared on codepen/jsbin).

You don't need a guitar in order to try it. You can just use the audio
player on the left (try to turn the amp on/off using the switch on the top
tight), or send a sin wave (menu below the audio player) and adjust the
freq/gain. You will see the frequency analyzers in action at different
stages of the amp. You'll also see the waveform in the oscilloscopes at
input and output. Sliders are for stabilizing the waveform. It's
interesting for looking at harmonics that are generated depending on the
different transfer functions I use for the tubes.

 If you're on a mac + soundcard + guitar, it plays in real time, and sound
and latency are comparable (well, assuming you've got the same audio buffer
size) with native references such as the JCM800 from Guitar Rig.

Lots of things are missing from these freq analyzer + oscilloscope, I'm
working on them: select freqs to zoom, freeze, display curves instead of
histograms, etc.
I'm also trying to break all external dependencies (global vars in freq
analyzer I was testing things). I'll post updated versions in case you'll
find that interesting.

**Comment by micbuffa** [comment]
Just in case: new version of the frequency analyser with embedded dat-gui + resizeable + just one ES6 class, no more external dependencies. I'm adding some zoom by selecting an area with the mouse + scale the Db vertical axis. You can already try the selection with mouse + drag.

Simple use:

let fa = new FrequencyAnalyzer(audioCtx, parentElem, label);
...
anyWebAudioNode.connect(fa);
fa.connect(audioCtx.destination);

fa.start(); // if you want the freq analyser to run its own requestAnimationFrame
                 // or if you have your own animation loop with raf, just call fa.update().
