### ISSUE TITLE
AudioBufferSource display

### ISSUE THREAD

**Issue by planUnd** [GoogleChrome/audion#82]
Dear All,

![dddd](https://user-images.githubusercontent.com/1295057/29568711-82617094-8751-11e7-80d1-de975617de70.JPG)

I have a question regarding the displayed graph:

Each time I execute a play on a PannerNode it generates a new AudioBufferSource item which is still connected to e.g. a filternode in the Graph if I don't disconnect manually. Is this only in the graph or is it that these items do not get garbage collected, somehow remain in the buffer...?

        if (this.loop > 0) {
            time = time + Math.ceil(this.duration*1000) + this.loop;
            this.looper = setTimeout(function () { that.play()}, time )
         }

Same webAudio Code visualized in Firefox looks fine. it also behaves differently. In firefox sound is good but in Chrome some soundsources crackle a bit after a few plays or depending on the computer the soundoutput squeaks and than silence...

Any Ideas 

thx Richard

**Comment by rtoy** [comment]
This is only on the graph.  Audion has no way of knowing that an object has been GCed. (Well assuming you've dropped the reference to the AudioBufferSourceNode and that it has finished playing.)

The chrome people are aware of this and want to provide, somehow, the necessary information ot audion so that the graph can be updated appropriately.

The cracking from Chrome is a different issue.  Search for existing bugs about this at crbug.com.  There are several related bugs, and it's being worked on.
