### ISSUE TITLE
Remove disposed oscillators from debug view

### ISSUE THREAD

**Issue by distante** [GoogleChrome/audion#83]
Since they are "one time only" nodes the extension should remove the oscillator graphics when they are stopped/disposed like Firefox debugger does.

Chrome:
![chrome](https://user-images.githubusercontent.com/5490201/34896878-c4d4e0a4-f7eb-11e7-837a-b348e4c60304.JPG)

Firefox:
![firefox](https://user-images.githubusercontent.com/5490201/34896890-cc929b60-f7eb-11e7-942f-041dc9f0c412.JPG)

**Comment by hoch** [comment]
This is because Chrome DevTool does not have a special hook that exposes collected AudioNode. This requires the implementation change in Chrome, meaning that there's nothing can be done within this extension.

**Comment by distante** [comment]
Hi @hoch thanks for your response. Would not be safe to asume that if a oscillator has no connections and it used `stop()` it will be disposed shortly?

**Comment by hoch** [comment]
AudioNode does not expose the number of active connections - meaning that the extension has to track all the connection by injecting a wrapper around the node. Also the destruction (after GC) of AudioNode must correspond to the deletion of the node in the visualization. Otherwise, it will be misleading one way or another. For example, if the code keeps the reference to an AudioNode even after disconnection and stop() call.

With that said, @chihuahua and I can review the PR if you're willing to contribute here. :)

**Comment by distante** [comment]
I promess I will **try** to do it.

**Comment by Arunass** [comment]
This issue applies to any AudioNode that is created.  Since AudioBufferSourceNodes are single use, they are continuously thrown away, but they pile up in the display and result in a potentially massive memory leak if this plug-in is enabled.
